# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3af39c266caf3cf79af6afdb0f87d94c61f644df8273182a964a846ad2793bfc3b57cf92511badd7c1dbbf19b90b2318ab51eef30ef6f83a057f0ba5e2465419

test:
  secret_key_base: 6d4fbe3eba3b920753b1708119a94c5e3edb0d94d95e7a551d00ba1e8c02a5d2cdea194d0c65242af468ad381b7e0000dff69e1dbd5a47d3a2b0114d94687c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
